version: '3.8'

services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env

  web:
    build: .
    container_name: ekologiya
    restart: unless-stopped
    volumes:
      - .:/code
      - ./gunicorn/logs:/gunicorn/logs
      - staticfiles:/code/staticfiles
      - media:/code/media
    env_file:
      - ./.env

  

volumes:
  media:
  staticfiles:
  postgres_data: