version: '3.8'

services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env

  web:
    build: .
    container_name: ekologiya
    restart: always
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  staticfiles:
  media:
  postgres_data: