version: "3.8"

services:
  db:
    container_name: ekologiya_db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env
    restart: always

  web:
    container_name: ekologiya_web
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    volumes:
      - ./:/app
      - ./locale:/home/app/web/locale
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  locale:
  staticfiles:
  media:
  postgres_data:
