version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ./.env


  web:
    build: .
    command: bash -c "python3 manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8001 --workers=4"
    volumes:
      - .:/code
      - ./static:/code/staticfiles
      - ./media:/code/media
      - ./locale:/code/locale
    ports:
      - '8001:8001'
    env_file:
      - ./.env

    depends_on:
      - db

volumes:
  postgres_data: